// Reviewed seed input. The storefront reads prices from Convex only.
// Source listings are benchmarks, not Floruvi stock or supplier commitments.
export const pricingRevision = "2026-09-14-retail-plus-40-v3";
export const deliveryFeeMinor = 9900;
export const pricingBenchmarks = [
  {
    slug: "butterhead-lettuce",
    packLabel: "1 head · 120–250 g",
    retailMinor: 7500,
    retailer: "OnlyHydroponics",
    city: "Delhi NCR",
    sourceUrl:
      "https://onlyhydroponics.in/products/lettuce-butterhead-hydroponics",
    sourceProduct:
      "Hydroponics Lettuce Butterhead- Organically Grown (high in iron and vitamins A & K) - Live Plant",
    sourcePack: "Small (120-250g) / 1 Full Plant",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "romaine-lettuce",
    packLabel: "1 head · 120–250 g",
    retailMinor: 7500,
    retailer: "OnlyHydroponics",
    city: "Delhi NCR",
    sourceUrl: "https://onlyhydroponics.in/products/hydroponic-lettuce-romaine",
    sourceProduct: "Hydroponic Lettuce Romaine- Organically Grown - Live plant",
    sourcePack: "Small (120-250g) / 1 Full Plant",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "lollo-rosso-lettuce",
    packLabel: "250 g",
    retailMinor: 10000,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/lettuce-lollo-rosso-premium",
    sourceProduct: "Lettuce Lollo Rosso Premium",
    sourcePack: "250 g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "red-oakleaf-lettuce",
    packLabel: "250 g",
    retailMinor: 21000,
    retailer: "Green Goblin",
    city: "Chennai",
    sourceUrl: "https://green-goblin.in/products/lettuce-oakleaf-red",
    sourceProduct: "Lettuce Oakleaf Red 250g",
    sourcePack: "Lettuce Oakleaf Red 250g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "iceberg-lettuce",
    packLabel: "200–300 g",
    retailMinor: 20000,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl:
      "https://www.kediaorganic.com/products/lettuce-iceberg-250gms-kedia-organic-agro-farms",
    sourceProduct: "Iceberg Lettuce – 200–300 g",
    sourcePack: "200-300 Gms",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "arugula",
    packLabel: "100 g",
    retailMinor: 9900,
    retailer: "OnlyHydroponics",
    city: "Delhi NCR",
    sourceUrl: "https://onlyhydroponics.in/products/hydroponic-rocket-leaves",
    sourceProduct:
      "Hydroponic Rocket Leaves- Organically Grown(packed with Vitamins B, C, E & K)",
    sourcePack: "Small (100g)",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "spinach",
    packLabel: "250 g",
    retailMinor: 7500,
    retailer: "OnlyHydroponics",
    city: "Delhi NCR",
    sourceUrl: "https://onlyhydroponics.in/products/hydroponic-spinach",
    sourceProduct: "Hydroponic Spinach - Organically Grown",
    sourcePack: "Small (250g)",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "curly-kale",
    packLabel: "100 g",
    retailMinor: 9900,
    retailer: "OnlyHydroponics",
    city: "Delhi NCR",
    sourceUrl:
      "https://onlyhydroponics.in/products/hydroponic-kale-curly-king-of-super-foods",
    sourceProduct:
      "Hydroponic Kale - Curly (king of super foods)- Organically Grown",
    sourcePack: "Small (100g)",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "lacinato-kale",
    packLabel: "100 g",
    retailMinor: 9900,
    retailer: "OnlyHydroponics",
    city: "Bengaluru",
    sourceUrl:
      "https://www.blr.onlyhydroponics.in/products/kale-lacinato-dinosaur-king-of-super-foods",
    sourceProduct:
      "Hydroponic Kale - Lacinato / Italian Tuscan (King of super foods)",
    sourcePack: "Small (100g)",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "swiss-chard",
    packLabel: "100 g",
    retailMinor: 9900,
    retailer: "OnlyHydroponics",
    city: "Delhi NCR",
    sourceUrl: "https://onlyhydroponics.in/products/hydroponic-swiss-chard",
    sourceProduct:
      "Hydroponic Swiss Chard- Organically Grown (THE nutritional powerhouse)",
    sourcePack: "Small (100g) / Cocktail",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "bok-choy",
    packLabel: "250 g",
    retailMinor: 14900,
    retailer: "OnlyHydroponics",
    city: "Delhi NCR",
    sourceUrl: "https://onlyhydroponics.in/products/hydroponic-bok-choy",
    sourceProduct:
      "Hydroponic Bok choy/Pok Choi- Organically Grown (packed with vitamins A & C)",
    sourcePack: "Medium (250g) / 2 Full Plants",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "sorrel",
    packLabel: "100 g",
    retailMinor: 10000,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/sorrel",
    sourceProduct: "Sorrel",
    sourcePack: "100 g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "endive",
    packLabel: "250 g",
    retailMinor: 5500,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/endive",
    sourceProduct: "Endive",
    sourcePack: "250 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "radicchio",
    packLabel: "200–300 g",
    retailMinor: 8000,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/radicchio",
    sourceProduct: "Radicchio",
    sourcePack: "200-300 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "amaranth-greens",
    packLabel: "1 bunch · 125–150 g",
    retailMinor: 7500,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/lal-math-leaves",
    sourceProduct: "Lal Math (Red Amaranth) – 1 Bunch",
    sourcePack: "1 Bunch (125-150 Gms without roots)",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "fenugreek-greens",
    packLabel: "1 bunch · 150–200 g",
    retailMinor: 7500,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl:
      "https://www.kediaorganic.com/products/methi-patta-fenugreek-leaves-150-gms-kedia-organic-agro-farms",
    sourceProduct: "Fenugreek Leaves (Methi) – 1 Bunch",
    sourcePack: "1 Bunch (150-200 Gms without roots)",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "napa-cabbage",
    packLabel: "250 g",
    retailMinor: 11000,
    retailer: "Green Goblin",
    city: "Chennai",
    sourceUrl: "https://green-goblin.in/products/chinese-cabbage",
    sourceProduct: "Chinese Cabbage 250g",
    sourcePack: "Chinese Cabbage 250g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "sweet-basil",
    packLabel: "100 g",
    retailMinor: 10000,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/basil-italian",
    sourceProduct: "Basil Italian",
    sourcePack: "100 gm",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "thai-basil",
    packLabel: "100 g",
    retailMinor: 14900,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/thai-sweet-basil",
    sourceProduct: "Thai Sweet Basil",
    sourcePack: "100 g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "holy-basil",
    packLabel: "250 g",
    retailMinor: 15000,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/tulsi-leaves",
    sourceProduct: "Tulsi Leaves (Fresh) – 250 g",
    sourcePack: "250 Gms",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "mint",
    packLabel: "1 bunch · 125–150 g",
    retailMinor: 4000,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/mint-leaves",
    sourceProduct: "Mint Leaves (Pudina) – 1 Bunch",
    sourcePack: "1 Bunch (125-150 Gms without roots)",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "coriander",
    packLabel: "1 bunch · 150–200 g",
    retailMinor: 7500,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl:
      "https://www.kediaorganic.com/products/coriander-leaves-150-gms-kedia-organic-agro-farms",
    sourceProduct: "Coriander Leaves (Dhaniya) – 1 Bunch",
    sourcePack: "1 Bunch (150-200 Gms without roots)",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "flat-leaf-parsley",
    packLabel: "100 g",
    retailMinor: 8500,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/parsley-flat",
    sourceProduct: "Parsley Flat",
    sourcePack: "100 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "curly-parsley",
    packLabel: "50 g",
    retailMinor: 5500,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/parsley-curled",
    sourceProduct: "Parsley Curled",
    sourcePack: "50 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "dill",
    packLabel: "1 bunch · 125–150 g",
    retailMinor: 7500,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/shepu-leaves",
    sourceProduct: "Shepu (Dill Leaves) – 1 Bunch",
    sourcePack: "1 Bunch (125-150 Gms without roots)",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "chives",
    packLabel: "100 g",
    retailMinor: 14900,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/chives-fresh",
    sourceProduct: "Chives Fresh",
    sourcePack: "100 gm",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "garlic-chives",
    packLabel: "100 g",
    retailMinor: 10000,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/garlic-chives",
    sourceProduct: "Garlic Chives",
    sourcePack: "100 g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "oregano",
    packLabel: "100 g",
    retailMinor: 15000,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/oregano-fresh",
    sourceProduct: "Oregano Fresh",
    sourcePack: "100 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "thyme",
    packLabel: "100 g",
    retailMinor: 12000,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/thyme-fresh",
    sourceProduct: "Thyme fresh",
    sourcePack: "100 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "rosemary",
    packLabel: "100 g",
    retailMinor: 12000,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/rosemerry",
    sourceProduct: "Rosemary Fresh",
    sourcePack: "100 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "sage",
    packLabel: "100 g",
    retailMinor: 15000,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/sage-fresh",
    sourceProduct: "Sage Fresh",
    sourcePack: "100 g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "shiso",
    packLabel: "100 g",
    retailMinor: 8500,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/shiso-leaf",
    sourceProduct: "Shiso Leaf",
    sourcePack: "100 g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "tarragon",
    packLabel: "100 g",
    retailMinor: 10000,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/tarragon-fresh",
    sourceProduct: "Tarragon Fresh",
    sourcePack: "100 g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "marjoram",
    packLabel: "100 g",
    retailMinor: 4000,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/sweet-marjoram-fresh",
    sourceProduct: "Sweet Marjoram Fresh",
    sourcePack: "100 g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "lemongrass",
    packLabel: "100 g",
    retailMinor: 3000,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/lemon-grass",
    sourceProduct: "Lemongrass (Fresh) – 1 Bunch",
    sourcePack: "1 Bunch (100Gms)",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "broccoli-microgreens",
    packLabel: "25 g",
    retailMinor: 16000,
    retailer: "Green Goblin",
    city: "Chennai",
    sourceUrl: "https://green-goblin.in/products/broccoli-microgreens-25g",
    sourceProduct: "Broccoli Microgreens 25g",
    sourcePack: "Broccoli Microgreens 25g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "radish-microgreens",
    packLabel: "50 g",
    retailMinor: 20000,
    retailer: "Green Goblin",
    city: "Chennai",
    sourceUrl: "https://green-goblin.in/products/radish-red-microgreen",
    sourceProduct: "Radish Red Microgreens 50g",
    sourcePack: "Radish Red Microgreens 50g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "pea-shoots",
    packLabel: "50 g",
    retailMinor: 20000,
    retailer: "Green Goblin",
    city: "Chennai",
    sourceUrl: "https://green-goblin.in/products/peas-shoot-microgreen",
    sourceProduct: "Pea Shoot Microgreens 50g",
    sourcePack: "Pea Shoot Microgreens 50g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "sunflower-shoots",
    packLabel: "50 g",
    retailMinor: 7900,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/microgreen-sunflowers",
    sourceProduct: "Microgreen Sunflower",
    sourcePack: "50 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "mustard-microgreens",
    packLabel: "50 g",
    retailMinor: 20000,
    retailer: "Green Goblin",
    city: "Chennai",
    sourceUrl: "https://green-goblin.in/products/mustard-microgreen",
    sourceProduct: "Mustard Microgreens 50g",
    sourcePack: "Mustard Microgreens 50g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "arugula-microgreens",
    packLabel: "25 g",
    retailMinor: 17000,
    retailer: "Green Goblin",
    city: "Chennai",
    sourceUrl: "https://green-goblin.in/products/roquette-microgreens-25g",
    sourceProduct: "Roquette Microgreens 25g",
    sourcePack: "Roquette Microgreens 25g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "amaranth-microgreens",
    packLabel: "50 g",
    retailMinor: 25000,
    retailer: "Green Goblin",
    city: "Chennai",
    sourceUrl: "https://green-goblin.in/products/amaranthus-microgreen",
    sourceProduct: "Amaranthus Microgreens 50g",
    sourcePack: "Amaranthus Microgreens 50g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "basil-microgreens",
    packLabel: "25 g",
    retailMinor: 16000,
    retailer: "Green Goblin",
    city: "Chennai",
    sourceUrl: "https://green-goblin.in/products/basil-microgreens-25g",
    sourceProduct: "Basil Microgreens 25g",
    sourcePack: "Basil Microgreens 25g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "wheatgrass",
    packLabel: "250 g",
    retailMinor: 30000,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/wheatgrassnearme",
    sourceProduct: "Fresh Wheatgrass – For Juicing",
    sourcePack: "250 Gms",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "cherry-tomatoes",
    packLabel: "250 g",
    retailMinor: 11000,
    retailer: "OnlyHydroponics",
    city: "Delhi NCR",
    sourceUrl: "https://onlyhydroponics.in/products/hydroponic-cherry-tomato",
    sourceProduct: "Hydroponic Cherry Tomato / Grape Tomato- Organically Grown",
    sourcePack: "Medium (250g) / Red",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "plum-tomatoes",
    packLabel: "250 g",
    retailMinor: 22000,
    retailer: "Green Goblin",
    city: "Chennai",
    sourceUrl: "https://green-goblin.in/products/roma-tomatoes-250g",
    sourceProduct: "Roma Tomatoes 250g",
    sourcePack: "Roma Tomatoes 250g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "cucumber",
    packLabel: "500 g",
    retailMinor: 6000,
    retailer: "OnlyHydroponics",
    city: "Delhi NCR",
    sourceUrl: "https://onlyhydroponics.in/products/hydroponic-cucumber",
    sourceProduct: "Hydroponic Snacking seedless Cucumber- Organically Grown",
    sourcePack: "500g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "bell-peppers",
    packLabel: "3 peppers · mixed colours",
    retailMinor: 25000,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/colour-capsicum-pack",
    sourceProduct: "Capsicum Colour Combo (Pack of 3)",
    sourcePack: "Pack of 3 ( Red -1 Yellow-1 Green - 1 )",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "green-chillies",
    packLabel: "100 g",
    retailMinor: 2500,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/chilli-less-spicy",
    sourceProduct: "Green Chillies (Less Spicy) – Fresh",
    sourcePack: "100 Gms",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "jalapeno-peppers",
    packLabel: "200 g",
    retailMinor: 6500,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/jalapeno-hot-chilly",
    sourceProduct: "Jalapeno Green Chilly",
    sourcePack: "200 gms",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "strawberries",
    packLabel: "250 g",
    retailMinor: 25000,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl:
      "https://www.kediaorganic.com/products/strawberry-400gms-kedia-organic-agro-farms",
    sourceProduct: "Indian Strawberries – Fresh & Seasonal",
    sourcePack: "250 Gms",
    sourceAvailable: false,
    observedOn: "2026-09-14",
  },
  {
    slug: "eggplant",
    packLabel: "250 g",
    retailMinor: 4000,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/brinjal-katheri",
    sourceProduct: "Brinjal Katheri (Small Round) – Fresh",
    sourcePack: "250 Gms",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "zucchini",
    packLabel: "150–200 g",
    retailMinor: 5700,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/zuchini-green",
    sourceProduct: "Zucchini Green – 150–200 g",
    sourcePack: "150-200 Gms",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "muskmelon",
    packLabel: "1 melon",
    retailMinor: 19000,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl:
      "https://www.kediaorganic.com/products/muskmelon-1kg-kedia-organic-agro-farms",
    sourceProduct: "Muskmelon (Kharbuja) – 1 Piece",
    sourcePack: "1 Piece",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "green-beans",
    packLabel: "250 g",
    retailMinor: 7600,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/french-beans",
    sourceProduct: "French Beans – Fresh",
    sourcePack: "250 Gms",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "spring-onions",
    packLabel: "1 bunch · 225–250 g",
    retailMinor: 10000,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/spring-onion",
    sourceProduct: "Spring Onions (Hara Pyaaz) – 1 Bunch",
    sourcePack: "1 Bunch (225-250 Gms without roots)",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "celery",
    packLabel: "250 g",
    retailMinor: 14900,
    retailer: "OnlyHydroponics",
    city: "Delhi NCR",
    sourceUrl:
      "https://onlyhydroponics.in/products/celery-the-famous-diet-food",
    sourceProduct: "Hydroponic Celery (The famous diet food)",
    sourcePack: "Small (250g)",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "radish",
    packLabel: "1 bunch · 450–500 g",
    retailMinor: 10000,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl:
      "https://www.kediaorganic.com/products/raddish-250gms-kedia-organic-agro-farms",
    sourceProduct: "White Radish (Mula) – 1 Bunch",
    sourcePack: "1 Bunch (450-500 Gms)",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "beetroot",
    packLabel: "250 g",
    retailMinor: 4500,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/beetroot",
    sourceProduct: "Beetroot – Fresh",
    sourcePack: "250 Gms",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "carrot",
    packLabel: "250 g",
    retailMinor: 5000,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/carrot-orange",
    sourceProduct: "Orange Carrots – Fresh",
    sourcePack: "250 Gms",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "ginger",
    packLabel: "250 g",
    retailMinor: 8500,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/ginger",
    sourceProduct: "Fresh Ginger (Adrak)",
    sourcePack: "250 Gms",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "turmeric",
    packLabel: "250 g",
    retailMinor: 6500,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/turmeric-fresh",
    sourceProduct: "Fresh Turmeric (Kachi Haldi)",
    sourcePack: "250 Gms",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "potato",
    packLabel: "1 kg",
    retailMinor: 8000,
    retailer: "Kedia Organic",
    city: "Mumbai",
    sourceUrl: "https://www.kediaorganic.com/products/potato",
    sourceProduct: "Potato (Aloo) – Fresh",
    sourcePack: "1 Kg",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "nasturtium-flowers",
    packLabel: "15–20 flowers",
    retailMinor: 35000,
    retailer: "Green Goblin",
    city: "Chennai",
    sourceUrl:
      "https://green-goblin.in/products/edible-flowers-nasturtium-packet",
    sourceProduct: "Edible Flowers: Nasturtium (Packet/15-20 Flowers)",
    sourcePack: "Edible Flowers: Nasturtium (Packet/15-20 Flowers)",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "green-oakleaf-lettuce",
    packLabel: "75 g",
    retailMinor: 8000,
    retailer: "Yodeli / Trueganic",
    city: "Mumbai",
    sourceUrl:
      "https://yodeli.in/products/truganic-organic-green-leafy-vegetables-hydroponic-oakleaf-lettuce",
    sourceProduct: "Oakleaf Lettuce (Hydroponic)",
    sourcePack: "75 g (product description)",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "baby-kale",
    packLabel: "250 g",
    retailMinor: 43700,
    retailer: "Sowfresh",
    city: "Delhi NCR",
    sourceUrl: "https://www.sowfresh.in/products/baby-kale",
    sourceProduct: "Baby Kale (250 gm)",
    sourcePack: "250 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "mustard-greens",
    packLabel: "200 g",
    retailMinor: 3800,
    retailer: "Healthy Buddha",
    city: "Bengaluru",
    sourceUrl: "https://healthybuddha.in/mustard-greens",
    sourceProduct: "Mustard Greens (Rai saag) (200gm)",
    sourcePack: "200 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "lollo-bionda-lettuce",
    packLabel: "200 g",
    retailMinor: 5000,
    retailer: "Shreenath Agro",
    city: "Mumbai",
    sourceUrl: "https://shreenathagro.com/product/lettuce-simpsons-butterhead/",
    sourceProduct: "Lollo Bionda Green, 200gm variant",
    sourcePack: "200 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "red-cabbage-microgreens",
    packLabel: "50 g",
    retailMinor: 17900,
    retailer: "Nutriofarms",
    city: "Bengaluru",
    sourceUrl: "https://nutriofarms.com/product/red-cabbage-microgreens/",
    sourceProduct: "Red cabbage Microgreens, 50 Grams variant",
    sourcePack: "50 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "kale-microgreens",
    packLabel: "50 g",
    retailMinor: 17900,
    retailer: "Nutriofarms",
    city: "Bengaluru",
    sourceUrl: "https://nutriofarms.com/product/kale-microgreens/",
    sourceProduct: "Kale Microgreens, 50 Grams variant",
    sourcePack: "50 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
  },
  {
    slug: "tatsoi",
    packLabel: "250 g",
    retailMinor: 14900,
    retailer: "OnlyHydroponics",
    city: "Delhi NCR",
    sourceUrl: "https://onlyhydroponics.in/products/hydroponic-bok-choy",
    sourceProduct:
      "Hydroponic Bok choy/Pok Choi- Organically Grown (packed with vitamins A & C)",
    sourcePack: "Medium (250g) / 2 Full Plants",
    sourceAvailable: false,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Floruvi launch price uses Hydroponic Bok choy/Pok Choi- Organically Grown (packed with vitamins A & C) as a category and pack comparator. Not an exact retail quote for tatsoi.",
  },
  {
    slug: "mizuna",
    packLabel: "100 g",
    retailMinor: 9900,
    retailer: "OnlyHydroponics",
    city: "Delhi NCR",
    sourceUrl: "https://onlyhydroponics.in/products/hydroponic-rocket-leaves",
    sourceProduct:
      "Hydroponic Rocket Leaves- Organically Grown(packed with Vitamins B, C, E & K)",
    sourcePack: "Small (100g)",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Floruvi launch price uses Hydroponic Rocket Leaves- Organically Grown(packed with Vitamins B, C, E & K) as a category and pack comparator. Not an exact retail quote for mizuna.",
  },
  {
    slug: "lemon-balm",
    packLabel: "100 g",
    retailMinor: 10000,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/tarragon-fresh",
    sourceProduct: "Tarragon Fresh",
    sourcePack: "100 g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Floruvi launch price uses Tarragon Fresh as a category and pack comparator. Not an exact retail quote for lemon-balm.",
  },
  {
    slug: "chervil",
    packLabel: "100 g",
    retailMinor: 10000,
    retailer: "Trikaya",
    city: "Mumbai / Bengaluru",
    sourceUrl: "https://trikaya.net/products/tarragon-fresh",
    sourceProduct: "Tarragon Fresh",
    sourcePack: "100 g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Floruvi launch price uses Tarragon Fresh as a category and pack comparator. Not an exact retail quote for chervil.",
  },
  {
    slug: "kohlrabi-microgreens",
    packLabel: "50 g",
    retailMinor: 17900,
    retailer: "Nutriofarms",
    city: "Bengaluru",
    sourceUrl: "https://nutriofarms.com/product/red-cabbage-microgreens/",
    sourceProduct: "Red cabbage Microgreens, 50 Grams variant",
    sourcePack: "50 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Floruvi launch price uses Red cabbage Microgreens, 50 Grams variant as a category and pack comparator. Not an exact retail quote for kohlrabi-microgreens.",
  },
  {
    slug: "beefsteak-tomatoes",
    packLabel: "250 g",
    retailMinor: 22000,
    retailer: "Green Goblin",
    city: "Chennai",
    sourceUrl: "https://green-goblin.in/products/roma-tomatoes-250g",
    sourceProduct: "Roma Tomatoes 250g",
    sourcePack: "Roma Tomatoes 250g",
    sourceAvailable: false,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Floruvi launch price uses Roma Tomatoes 250g as a category and pack comparator. Not an exact retail quote for beefsteak-tomatoes.",
  },
  {
    slug: "watercress",
    packLabel: "100 g",
    retailMinor: 16900,
    retailer: "Supple Agro",
    city: "Delhi NCR",
    sourceUrl: "https://microgreens.co.in/products/watercress",
    sourceProduct: "Watercress",
    sourcePack: "100gm",
    sourceAvailable: false,
    observedOn: "2026-09-14",
    basis: "exact",
  },
  {
    slug: "viola-flowers",
    packLabel: "40 g",
    retailMinor: 25000,
    retailer: "Supple Agro",
    city: "Delhi NCR",
    sourceUrl: "https://microgreens.co.in/products/assorted-mix",
    sourceProduct: "Assorted Mix Edible Flower",
    sourcePack: "40gm",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Floruvi single-variety launch price uses a mixed edible flower pack as a category comparator; not an exact quote for this variety. Source heading says 40gm while body also says 35 flowers and shipping weight 0.1kg. Floruvi sells 40 g.",
  },
  {
    slug: "pansy-flowers",
    packLabel: "40 g",
    retailMinor: 25000,
    retailer: "Supple Agro",
    city: "Delhi NCR",
    sourceUrl: "https://microgreens.co.in/products/assorted-mix",
    sourceProduct: "Assorted Mix Edible Flower",
    sourcePack: "40gm",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Floruvi single-variety launch price uses a mixed edible flower pack as a category comparator; not an exact quote for this variety. Source heading says 40gm while body also says 35 flowers and shipping weight 0.1kg. Floruvi sells 40 g.",
  },
  {
    slug: "calendula-petals",
    packLabel: "40 g",
    retailMinor: 25000,
    retailer: "Supple Agro",
    city: "Delhi NCR",
    sourceUrl: "https://microgreens.co.in/products/assorted-mix",
    sourceProduct: "Assorted Mix Edible Flower",
    sourcePack: "40gm",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Floruvi single-variety launch price uses a mixed edible flower pack as a category comparator; not an exact quote for this variety. Source heading says 40gm while body also says 35 flowers and shipping weight 0.1kg. Floruvi sells 40 g.",
  },
  {
    slug: "borage-flowers",
    packLabel: "40 g",
    retailMinor: 25000,
    retailer: "Supple Agro",
    city: "Delhi NCR",
    sourceUrl: "https://microgreens.co.in/products/assorted-mix",
    sourceProduct: "Assorted Mix Edible Flower",
    sourcePack: "40gm",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Floruvi single-variety launch price uses a mixed edible flower pack as a category comparator; not an exact quote for this variety. Source heading says 40gm while body also says 35 flowers and shipping weight 0.1kg. Floruvi sells 40 g.",
  },
  {
    slug: "beet-microgreens",
    packLabel: "50 g",
    retailMinor: 14900,
    retailer: "Nutriofarms",
    city: "Bengaluru",
    sourceUrl: "https://nutriofarms.com/product/beet-microgreens/",
    sourceProduct: "beet Microgreens, 50 Grams variant",
    sourcePack: "50 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "exact",
  },
  {
    slug: "fenugreek-microgreens",
    packLabel: "50 g",
    retailMinor: 14900,
    retailer: "Nutriofarms",
    city: "Bengaluru",
    sourceUrl: "https://nutriofarms.com/product/fenugreek-microgreens/",
    sourceProduct: "fenugreek Microgreens, 50 Grams variant",
    sourcePack: "50 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "exact",
  },
  {
    slug: "garden-cress-microgreens",
    packLabel: "50 g",
    retailMinor: 17900,
    retailer: "Nutriofarms",
    city: "Bengaluru",
    sourceUrl: "https://nutriofarms.com/product/garden-cress-microgreens/",
    sourceProduct: "garden-cress Microgreens, 50 Grams variant",
    sourcePack: "50 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "exact",
  },
  {
    slug: "coriander-microgreens",
    packLabel: "50 g",
    retailMinor: 14900,
    retailer: "Nutriofarms",
    city: "Bengaluru",
    sourceUrl: "https://nutriofarms.com/product/coriander-microgreens/",
    sourceProduct: "coriander Microgreens, 50 Grams variant",
    sourcePack: "50 g",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "exact",
  },
  {
    slug: "radish-microgreens-live-tray",
    packLabel: "1 live tray",
    retailMinor: 13000,
    retailer: "NayaGreens",
    city: "Bengaluru",
    sourceUrl: "https://nayagreens.com/microgreens-live/",
    sourceProduct: "Fenugreek Microgreens – Live Tray",
    sourcePack: "1 live tray; dimensions and harvest weight not stated",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Live-tray launch price uses the listed ₹130 tray benchmark. Tray dimensions and harvest weights are not matched or promised. Other varieties use the Fenugreek tray as a category comparator.",
  },
  {
    slug: "pea-microgreens-live-tray",
    packLabel: "1 live tray",
    retailMinor: 13000,
    retailer: "NayaGreens",
    city: "Bengaluru",
    sourceUrl: "https://nayagreens.com/microgreens-live/",
    sourceProduct: "Fenugreek Microgreens – Live Tray",
    sourcePack: "1 live tray; dimensions and harvest weight not stated",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Live-tray launch price uses the listed ₹130 tray benchmark. Tray dimensions and harvest weights are not matched or promised. Other varieties use the Fenugreek tray as a category comparator.",
  },
  {
    slug: "sunflower-microgreens-live-tray",
    packLabel: "1 live tray",
    retailMinor: 13000,
    retailer: "NayaGreens",
    city: "Bengaluru",
    sourceUrl: "https://nayagreens.com/microgreens-live/",
    sourceProduct: "Fenugreek Microgreens – Live Tray",
    sourcePack: "1 live tray; dimensions and harvest weight not stated",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Live-tray launch price uses the listed ₹130 tray benchmark. Tray dimensions and harvest weights are not matched or promised. Other varieties use the Fenugreek tray as a category comparator.",
  },
  {
    slug: "broccoli-microgreens-live-tray",
    packLabel: "1 live tray",
    retailMinor: 13000,
    retailer: "NayaGreens",
    city: "Bengaluru",
    sourceUrl: "https://nayagreens.com/microgreens-live/",
    sourceProduct: "Fenugreek Microgreens – Live Tray",
    sourcePack: "1 live tray; dimensions and harvest weight not stated",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Live-tray launch price uses the listed ₹130 tray benchmark. Tray dimensions and harvest weights are not matched or promised. Other varieties use the Fenugreek tray as a category comparator.",
  },
  {
    slug: "fenugreek-microgreens-live-tray",
    packLabel: "1 live tray",
    retailMinor: 13000,
    retailer: "NayaGreens",
    city: "Bengaluru",
    sourceUrl: "https://nayagreens.com/microgreens-live/",
    sourceProduct: "Fenugreek Microgreens – Live Tray",
    sourcePack: "1 live tray; dimensions and harvest weight not stated",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Live-tray launch price uses the listed ₹130 tray benchmark. Tray dimensions and harvest weights are not matched or promised. Other varieties use the Fenugreek tray as a category comparator.",
  },
  {
    slug: "red-amaranth-microgreens-live-tray",
    packLabel: "1 live tray",
    retailMinor: 13000,
    retailer: "NayaGreens",
    city: "Bengaluru",
    sourceUrl: "https://nayagreens.com/microgreens-live/",
    sourceProduct: "Amaranthus Red Microgreens – Live Tray",
    sourcePack: "1 live tray; dimensions and harvest weight not stated",
    sourceAvailable: true,
    observedOn: "2026-09-14",
    basis: "comparable",
    basisNote:
      "Live-tray launch price uses the listed ₹130 tray benchmark. Tray dimensions and harvest weights are not matched or promised. Other varieties use the Fenugreek tray as a category comparator.",
  },
];
